apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: Cloudflare Tunnel
        property: TUNNEL_TOKEN
