apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleet-vulndb
  namespace: fleet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  volumeName: pvc-8d723f76-81e8-47ec-9f04-c1b9a0cbe334
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleet-logs
  namespace: fleet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  volumeName: pvc-9f43e49a-af36-4c25-a93b-c934a446108e
  resources:
    requests:
      storage: 5Gi
