apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleet-vulndb
  namespace: fleet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleet-logs
  namespace: fleet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 5Gi
