apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  volumeName: pvc-3f1d6c20-3384-4a6c-926a-104f26496c44
  resources:
    requests:
      storage: 1Gi
