apiVersion: v1
kind: ConfigMap
metadata:
  name: homelab-ca
  namespace: cloudflare
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBmDCCAT2gAwIBAgIUPA8o2dqfYaBYR2D3KbvshvdWEbMwCgYIKoZIzj0EAwIw
    GTEXMBUGA1UEAwwOaG9tZWxhYi1rM3MtY2EwHhcNMjYwNDAzMDMwNTQ3WhcNMzYw
    MzMxMDMwNTQ3WjAZMRcwFQYDVQQDDA5ob21lbGFiLWszcy1jYTBZMBMGByqGSM49
    AgEGCCqGSM49AwEHA0IABL6K/EaAYH9o+NE4AGFKED8ADhO5QxGs5hWkLd0GsjYJ
    3X4sMWEfgHby69l1J0p9clvm8bg0alF2g24bBx++f7qjYzBhMB0GA1UdDgQWBBSD
    lqlnrsPh4eQxFu9Qrj6jsTCQMzAfBgNVHSMEGDAWgBSDlqlnrsPh4eQxFu9Qrj6j
    sTCQMzAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwICBDAKBggqhkjOPQQD
    AgNJADBGAiEAtUj8N5zECJauanNTNkiKdPx0xa7iwD1/V2q8/YVbsb8CIQC02Zvq
    AzYQtkO2TkW918/40s7ob2/i9td8ddStPKODbA==
    -----END CERTIFICATE-----
