apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - authentik-server-deployment.yaml
  - authentik-worker-deployment.yaml
  - certificate.yaml
