apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - postgres-statefulset.yaml
  - nginx-config.yaml
  - media-pvc.yaml
  - authentik-server-deployment.yaml
  - authentik-worker-deployment.yaml
  - certificate.yaml
  - backup-storage-pvc.yaml
  - backup-cronjob.yaml
