apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-data
  namespace: portainer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  volumeName: pvc-9843bad9-77e7-42ee-8e68-d301f724a3e0
  resources:
    requests:
      storage: 10Gi
