apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-networking
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure-core
  path: ./infrastructure/networking
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
