apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-core
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure-sources
  path: ./infrastructure/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
