apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello
  namespace: hello-world
  annotations:
    # Enable Funnel to expose service publicly with Let's Encrypt certificates
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: hello-world
      port:
        number: 443
