apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fleet-buffering
  namespace: fleet-sandbox
spec:
  buffering:
    maxRequestBodyBytes: 2147483648  # 2048m
    memRequestBodyBytes: 131072      # 128k
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: fleet-transport
  namespace: fleet-sandbox
spec:
  forwardingTimeouts:
    dialTimeout: 600s
    responseHeaderTimeout: 600s
    readIdleTimeout: 600s
