apiVersion: v1
kind: Namespace
metadata:
  name: onepassword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
    spec:
      containers:
      - name: connect-api
        image: 1password/connect-api:1.7.3
        env:
        - name: OP_SESSION
          valueFrom:
            secretKeyRef:
              name: op-credentials
              key: 1password-credentials.json
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      - name: connect-sync
        image: 1password/connect-sync:1.7.3
        env:
        - name: OP_SESSION
          valueFrom:
            secretKeyRef:
              name: op-credentials
              key: 1password-credentials.json
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: shared-data
          mountPath: /home/opuser/.op/data
      volumes:
      - name: shared-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  selector:
    app: onepassword-connect
  ports:
  - port: 8080
    targetPort: 8080
    name: http
