apiVersion: v1
kind: Namespace
metadata:
  name: onepassword
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      version: "1.15.1"
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  values:
    connect:
      credentials: op-credentials
      credentials_key: 1password-credentials.json
    operator:
      create: false
      token:
        value: ""
