apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-storage-fleet
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10gb-nas.kitzy.net
    path: /volume1/k8s-backups
  mountOptions:
    - hard
    - nfsvers=4.1
    - timeo=600
    - retrans=2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-storage-scanopy
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10gb-nas.kitzy.net
    path: /volume1/k8s-backups
  mountOptions:
    - hard
    - nfsvers=4.1
    - timeo=600
    - retrans=2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-storage-authentik
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10gb-nas.kitzy.net
    path: /volume1/k8s-backups
  mountOptions:
    - hard
    - nfsvers=4.1
    - timeo=600
    - retrans=2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-storage-portainer
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10gb-nas.kitzy.net
    path: /volume1/k8s-backups
  mountOptions:
    - hard
    - nfsvers=4.1
    - timeo=600
    - retrans=2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-storage-fleet-sandbox
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10gb-nas.kitzy.net
    path: /volume1/k8s-backups
  mountOptions:
    - hard
    - nfsvers=4.1
    - timeo=600
    - retrans=2
