apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nfs-storageclass.yaml
  - nfs-pv.yaml
  - nfs-pvc.yaml
  - external-secrets.yaml
  - retention-cleanup-cronjob.yaml