apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
  namespace: backups
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: backup-storage