apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleet
  namespace: fleet-sandbox
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: fleet-sandbox-fleet-buffering@kubernetescrd
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: fleet-sandbox-fleet-transport@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - fleet-sandbox.kitzy.net
    secretName: fleet-sandbox-letsencrypt-tls
  rules:
  - host: fleet-sandbox.kitzy.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fleet
            port:
              number: 8080
