---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fleet-backup-secrets
  namespace: backups
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: fleet-secrets
    creationPolicy: Owner
  data:
    - secretKey: mysql-password
      remoteRef:
        key: Fleet Secrets
        property: MYSQL_ROOT_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scanopy-backup-secrets
  namespace: backups
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: scanopy-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: Scanopy Secrets
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-backup-secrets
  namespace: backups
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgres-user
      remoteRef:
        key: authentik-secrets
        property: POSTGRES_USER
    - secretKey: postgres-db
      remoteRef:
        key: authentik-secrets
        property: POSTGRES_DB
    - secretKey: postgres-password
      remoteRef:
        key: authentik-secrets
        property: POSTGRES_PASSWORD
