apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-world-tls
  namespace: hello-world
spec:
  secretName: hello-world-tls
  duration: 2160h     # 90 days
  renewBefore: 720h   # renew 30 days before expiry
  privateKey:
    rotationPolicy: Always
  dnsNames:
  - hello.kitzy.net
  - hello-world.hello-world.svc.cluster.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
