apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
  namespace: fleet
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: backup-storage-fleet
  resources:
    requests:
      storage: 1Ti
